FROM wordpress

# Permissions fix (important)
# (see https://github.com/docker/docker/issues/2259)
RUN usermod -u 1000 www-data

# wp cli
RUN apt-get update \
 && apt-get install --no-install-recommends -y \
      sudo less mariadb-client-core-10.0 \
 && apt-get clean \
 && curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
 && chmod +x /usr/local/bin/wp

